apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sk016-maintq-fe-pvc-v2
    namespace: skala3-ai1
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
